package com.pwms.notification.service;

import com.pwms.notification.dto.*;
import com.pwms.notification.exception.NotificationNotFoundException;
import com.pwms.notification.interfaces.NotificationIntf;
import com.pwms.notification.model.Notification;
import com.pwms.notification.model.Notification.*;
import com.pwms.notification.repository.NotificationRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class NotificationService implements NotificationIntf {

    private final NotificationRepository notifRepo;

    // ── Triggered by patient module ───────────────────────────

    @Override
    public void notifyNewPatientRegistered(int patientId, int adminId) {
        save(NotificationRequestDTO.builder()
                .receiverId(adminId)
                .receiverType(ReceiverType.ADMIN)
                .notificationType(NotificationType.NEW_PATIENT_REGISTERED)
                .patientId(patientId)
                .build());
    }

    // ── Triggered by progress module ──────────────────────────

    @Override
    public void notifyActivityAppreciation(int patientId, int planId,
                                           String activityName) {
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.ACTIVITY_APPRECIATION)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Great job completing " + activityName + "!");
    }

    @Override
    public void notifyActivityReminder(int patientId, int planId,
                                       String activityName) {
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.ACTIVITY_REMINDER)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Reminder: Complete " + activityName + " today!");
    }

    @Override
    public void notifyPlanCompleted(int patientId, int planId, int adminId) {
        // Notify patient
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.PLAN_COMPLETED)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Congratulations! You have completed your wellness plan.");

        // Notify admin to generate report
        save(NotificationRequestDTO.builder()
                        .receiverId(adminId)
                        .receiverType(ReceiverType.ADMIN)
                        .notificationType(NotificationType.GENERATE_REPORT_REMINDER)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Patient " + patientId + " has completed their plan. Please generate a report.");
    }

    @Override
    public void notifyWeeklySummary(int patientId, int planId,
                                    double completionPct) {
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.WEEKLY_SUMMARY)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Weekly progress: " + completionPct + "% complete. Keep it up!");
    }

    // ── Triggered by report module ────────────────────────────

    @Override
    public void notifyReportShared(int patientId, int planId) {
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.REPORT_SHARED)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Your wellness report has been generated by your doctor. Please review it.");
    }

    // ── Triggered by wellness plan module ─────────────────────

    @Override
    public void notifyAppointmentReminder(int patientId, int planId) {
        save(NotificationRequestDTO.builder()
                        .receiverId(patientId)
                        .receiverType(ReceiverType.PATIENT)
                        .notificationType(NotificationType.APPOINTMENT_REMINDER)
                        .patientId(patientId)
                        .planId(planId)
                        .build(),
                "Your wellness plan is complete. Please book an appointment " +
                        "with your doctor for further analysis.");
    }

    // ── Generic trigger ───────────────────────────────────────

    @Override
    public void sendNotification(NotificationRequestDTO request) {
        save(request);
    }

    // ── Read operations ───────────────────────────────────────

    @Override
    public List<NotificationDTO> getNotificationsForPatient(int patientId)
            throws NotificationNotFoundException {
        List<Notification> list = notifRepo.findByReceiverIdAndReceiverType(
                patientId, ReceiverType.PATIENT);
        if (list.isEmpty()) throw new NotificationNotFoundException(
                "No notifications found for patientId: " + patientId);
        return list.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Override
    public List<NotificationDTO> getUnreadForPatient(int patientId)
            throws NotificationNotFoundException {
        List<Notification> list = notifRepo.findByReceiverIdAndReceiverTypeAndIsRead(
                patientId, ReceiverType.PATIENT, false);
        if (list.isEmpty()) throw new NotificationNotFoundException(
                "No unread notifications for patientId: " + patientId);
        return list.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Override
    public List<NotificationDTO> getNotificationsForAdmin(int adminId)
            throws NotificationNotFoundException {
        List<Notification> list = notifRepo.findByReceiverIdAndReceiverType(
                adminId, ReceiverType.ADMIN);
        if (list.isEmpty()) throw new NotificationNotFoundException(
                "No notifications found for adminId: " + adminId);
        return list.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Override
    public List<NotificationDTO> getUnreadForAdmin(int adminId)
            throws NotificationNotFoundException {
        List<Notification> list = notifRepo.findByReceiverIdAndReceiverTypeAndIsRead(
                adminId, ReceiverType.ADMIN, false);
        if (list.isEmpty()) throw new NotificationNotFoundException(
                "No unread notifications for adminId: " + adminId);
        return list.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Override
    public NotificationDTO markAsRead(int notificationId)
            throws NotificationNotFoundException {
        Notification n = notifRepo.findById(notificationId)
                .orElseThrow(() -> new NotificationNotFoundException(
                        "Notification not found with id: " + notificationId));
        n.setRead(true);
        return toDTO(notifRepo.save(n));
    }

    // ── Internal save helpers ─────────────────────────────────

    // Save with auto-generated message based on type
    private void save(NotificationRequestDTO req) {
        save(req, buildMessage(req.getNotificationType(), req.getPatientId()));
    }

    // Save with explicit message
    private void save(NotificationRequestDTO req, String message) {
        notifRepo.save(Notification.builder()
                .receiverId(req.getReceiverId())
                .receiverType(req.getReceiverType())
                .notificationType(req.getNotificationType())
                .message(message)
                .patientId(req.getPatientId())
                .planId(req.getPlanId())
                .isRead(false)
                .build());
    }

    // Fallback message builder for generic trigger
    private String buildMessage(Notification.NotificationType type, Integer patientId) {
        return switch (type) {
            case NEW_PATIENT_REGISTERED     -> "New patient " + patientId + " has been registered.";
            case PLAN_COMPLETED             -> "Wellness plan completed.";
            case GENERATE_REPORT_REMINDER   -> "Please generate report for patient " + patientId + ".";
            case APPOINTMENT_REMINDER       -> "Please book a doctor appointment.";
            case REPORT_SHARED              -> "Your wellness report is ready.";
            case WEEKLY_SUMMARY             -> "Your weekly summary is ready.";
            case ACTIVITY_REMINDER          -> "You have pending activities today.";
            case ACTIVITY_APPRECIATION      -> "Great job completing your activity!";
        };
    }

    // ── Mapper ────────────────────────────────────────────────
    private NotificationDTO toDTO(Notification n) {
        return NotificationDTO.builder()
                .notificationId(n.getNotificationId())
                .receiverId(n.getReceiverId())
                .receiverType(n.getReceiverType().name())
                .notificationType(n.getNotificationType().name())
                .message(n.getMessage())
                .patientId(n.getPatientId())
                .planId(n.getPlanId())
                .isRead(n.isRead())
                .createdAt(n.getCreatedAt())
                .build();
    }
}